name: flutter_clean_architecture
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Functional programming tools
  dartz: ^0.10.1
  # Object equality comparison
  equatable: ^2.0.5
  # State management for Flutter
  flutter_bloc: ^8.1.3
  # Dependency injection
  get_it: ^7.6.4
  # HTTP requests
  http: ^1.1.0
  # Persistent storage for key-value pairs
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
