name: flutter_clean_architecture
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Object equality comparison
  equatable: ^2.0.5
  # State management for Flutter
  flutter_bloc: ^8.1.3
  # Dependency injection
  get_it: ^7.6.4
  # HTTP requests
  retrofit: ^4.0.3
  # SQLite database library for Flutter
  floor: ^1.4.2
  # Internationalization and localization support
  intl: ^0.19.0
  # Cached network image loading for Flutter
  cached_network_image: ^3.3.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.5
  floor_generator: ^1.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
